version: '3.9'

services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - micro-net

  discovery-server:
    build:
      context: .
      dockerfile: discovery-server/Dockerfile
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 5000
    depends_on:
      - logstash
    networks:
      - micro-net

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 5000
    depends_on:
      - discovery-server
      - logstash
    networks:
      - micro-net

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 5000
    depends_on:
      - mysql
      - discovery-server
      - logstash
    networks:
      - micro-net

  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    container_name: product-service
    ports:
      - "8082:8082"
    environment:
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 5000
    depends_on:
      - mysql
      - discovery-server
      - logstash
    networks:
      - micro-net

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: order-service
    ports:
      - "8083:8083"
    environment:
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 5000
    depends_on:
      - mysql
      - discovery-server
      - logstash
    networks:
      - micro-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - micro-net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.0
    container_name: logstash
    ports:
      - "5000:5000"
    volumes:
      - ./docker/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./docker/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    depends_on:
      - elasticsearch
    networks:
      - micro-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - micro-net

volumes:
  mysql-data:
  es-data:

networks:
  micro-net:
    driver: bridge
