server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://mysql:3306/userdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

logging:
  file:
    name: /var/log/services/user-service.log
