server:
  port: 8083

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://mysql:3306/orderdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

logging:
  file:
    name: /var/log/services/order-service.log
